name: codes
description: Flutter template code.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  # sdk: ">=2.7.0 <3.0.0"
  sdk: ">=2.12.0 <3.0.0"
  
  

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  json_annotation: any

  flutter_base:
    path: plugins/flutter_base
  json_model:
    path: plugins/json_model
  retrofit:
    path: plugins/retrofit_annotation

  # webview_flutter: ^2.0.3
  # flutter_webview_plugin: ^0.3.11

  package_info: ^2.0.0

  # flutter_swiper: ^1.1.6
  # wc_flutter_share: ^0.4.0 #分享
  # provider: ^5.0.0 #State

    #元组
  # tuple: ^2.0.0

  url_launcher: ^6.0.3 #启动第三方app

  # dio_cookie_manager: ^2.0.0
  # cookie_jar: ^3.0.1
  shared_preferences: ^2.0.5 #本地json对象存储
  localstorage: ^4.0.0+1 

  #网络变化
  connectivity: ^3.0.3
  permission_handler: ^6.1.1
  # image_picker: ^0.7.4 
  # qr_code_scanner: ^0.4.0
  image_gallery_saver: ^1.6.8 

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:

  retrofit_generator:
    path: plugins/retrofit_generator

  build_runner: any
  json_serializable: any

# dependency_overrides:
#   retrofit_generator:
#     path: plugins/generator

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true